### ISSUE TITLE
The panel returns a 500 forbidden error when trying to access the API docs

### ISSUE THREAD

**Issue by axdynx** [pelican-dev/panel#471]
### Current Behavior

![image](https://github.com/pelican-dev/panel/assets/66255038/8154ae03-d908-4fb9-8768-3eab80c9b48b)
The panel returns a 500 forbidden error when trying to access the API docs

### Expected Behavior

In previous versions, I could correctly access the API docs pages (which are not complete by the way)

### Steps to Reproduce

Install and configure Pelican and try to access the pages:
- https://domainname/docs/api/application
- https://domainname/docs/api/remote
- https://domainname/docs/api/client

### Panel Version

1.0.0-beta6

### Wings Version

1.0.0-beta3

### Error Logs

```bash
[previous exception] [object] (ErrorException(code: 0): Undefined variable $api at /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/storage/framework/views/e179c0afa35e48067a255a4d1f2fc722.php:13)
[stacktrace]
#0 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/storage/framework/views/e179c0afa35e48067a255a4d1f2fc722.php(13): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(123): require('...')
#3 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(124): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#4 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#5 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(22): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#6 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(73): Livewire\\Mechanisms\\ExtendBlade\\ExtendedCompilerEngine->evaluatePath()
#7 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(10): Illuminate\\View\\Engines\\CompilerEngine->get()
#8 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/View/View.php(208): Livewire\\Mechanisms\\ExtendBlade\\ExtendedCompilerEngine->get()
#9 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/View/View.php(191): Illuminate\\View\\View->getContents()
#10 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/View/View.php(160): Illuminate\\View\\View->renderContents()
#11 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Http/Response.php(70): Illuminate\\View\\View->render()
#12 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#13 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(918): Illuminate\\Http\\Response->__construct()
#14 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(885): Illuminate\\Routing\\Router::toResponse()
#15 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Routing\\Router->prepareResponse()
#16 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#17 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/dedoc/scramble/src/Http/Middleware/RestrictedDocsAccess.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Dedoc\\Scramble\\Http\\Middleware\\RestrictedDocsAccess->handle()
#19 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/app/Http/Middleware/RequireTwoFactorAuthentication.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\RequireTwoFactorAuthentication->handle()
#21 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/app/Http/Middleware/LanguageMiddleware.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\LanguageMiddleware->handle()
#23 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#25 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#27 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#29 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#31 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#33 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#34 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#36 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#38 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#40 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#41 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#42 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#43 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#44 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#45 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle()
#47 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#49 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#50 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#52 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#53 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#55 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#57 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#59 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#61 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#63 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#64 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1183): Illuminate\\Foundation\\Http\\Kernel->handle()
#65 /var/www/vhosts/adkynet.com/panel-beta.adkynet.com/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest()
#66 {main}
"}
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RMartinOscar** [comment]
Hey there's indeed no [$api](https://github.com/search?q=repo%3Apelican-dev%2Fpanel+%2F%5C%24api%2F&type=code) in the whole code (i tried Canary, beta1-beta6) i don't know what happened but there's something wrong

**Comment by RMartinOscar** [comment]
Could you hop on [Discord](https://discord.gg/pelican-panel) so i can help you with that in [General](https://discord.com/channels/1218730176297439332/1218733868253708348) ?

**Comment by Boy132** [comment]
Run `php artisan view:clear` and try again.

**Comment by axdynx** [comment]
> Member

It didn't work

**Comment by axdynx** [comment]
> Run `php artisan view:clear` and try again.

It didn't work
